# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
